# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
